# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
